# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
